# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
